# .streamlit/secrets.toml
OPENAI_API_KEY = "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"
